# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
